# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
